# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
